# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
